# Carga helpers de RN (no lo quites)
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve("react-native/scripts/react_native_pods.rb", {paths: [process.argv[1]]})', __dir__
]).strip

platform :ios, '16.0'
prepare_react_native_project!
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

target 'wirawallet' do
  use_frameworks! :linkage => :static

  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'RNNotifee',     :path => '../node_modules/@notifee/react-native'
  pod 'RNFBApp',       :path => '../node_modules/@react-native-firebase/app'
  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'
end

post_install do |installer|
  react_native_post_install(installer, :mac_catalyst_enabled => false)
  installer.pods_project.targets.each do |t|
    t.build_configurations.each { |c| c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0' }
  end
end
