export const StackNav = {
  Splash: 'Splash',
  OnBoarding: 'OnBoarding',
  AuthNavigation: 'AuthNavigation',
  TabNavigation: 'TabNavigation',

  // Recovery
  MyGuardiansStatus: 'MyGuardiansStatus',
  RecoveryUser1Pin: 'RecoveryUser1Pin',
  RecoveryUser2Pin: 'RecoveryUser2Pin',
  RecoveryFinalize: 'RecoveryFinalize',

  // Nuevas rutas para Mi Voto
  SearchTable: 'SearchTable',
  TableDetail: 'TableDetail',
  CameraScreen: 'CameraScreen',
  CameraPermissionTest: 'CameraPermissionTest',
  PhotoReviewScreen: 'PhotoReviewScreen',
  PhotoConfirmationScreen: 'PhotoConfirmationScreen',
  SuccessScreen: 'SuccessScreen',
  // Atestiguar Acta
  WitnessRecord: 'WitnessRecord',
  WhichIsCorrectScreen: 'WhichIsCorrectScreen',
  RecordReviewScreen: 'RecordReviewScreen',
  RecordCertificationScreen: 'RecordCertificationScreen',
  // Anunciar Conteo
  AnnounceCount: 'AnnounceCount',
  SearchCountTable: 'SearchCountTable',
  CountTableDetail: 'CountTableDetail',
  // Mis Atestiguamientos
  MyWitnesses: 'MyWitnesses',
  MyWitnessesListScreen: 'MyWitnessesListScreen',
  MyWitnessesDetailScreen: 'MyWitnessesDetailScreen',

  // Profile y configuración
  PersonalDetails: 'PersonalDetails',
  RecuperationQR: 'RecuperationQR',
  Guardians: 'Guardians',
  GuardiansAdmin: 'GuardiansAdmin',
  AddGuardians: 'AddGuardians',
  SelectLanguage: 'SelectLanguage',
  PushNotification: 'PushNotification',
  HelpCenter: 'HelpCenter',
  FAQScreen: 'FAQScreen',
  PrivacyPolicies: 'PrivacyPolicies',
  ChangePinVerify: 'ChangePinVerify',
  ChangePinNew: 'ChangePinNew',
  ChangePinNewConfirm: 'ChangePinNewConfirm',
  TermsAndCondition: 'TermsAndCondition',
  Notification: 'Notification',
  NotificationDetails: 'NotificationDetails',
};

export const TabNav = {
  HomeScreen: 'HomeScreen',
  Profile: 'Profile',
};

export const AuthNav = {
  Connect: 'Connect',
  OnBoarding: 'OnBoarding',
  Login: 'Login',
  LoginUser: 'LoginUser',
  SignUp: 'SignUp',
  RegisterUser1: 'RegisterUser1',
  RegisterUser2: 'RegisterUser2',
  RegisterUser3: 'RegisterUser3',
  RegisterUser4: 'RegisterUser4',
  RegisterUser5: 'RegisterUser5',
  RegisterUser6: 'RegisterUser6',
  RegisterUser7: 'RegisterUser7',
  RegisterUser8: 'RegisterUser8',
  RegisterUser9: 'RegisterUser9',
  RegisterUser10: 'RegisterUser10',
  RegisterUser11: 'RegisterUser11',
  AccountLock: 'AccountLock',
  SelectRecuperation: 'SelectRecuperation',
  ConditionsRegister: 'ConditionsRegister',
  SignUpWithMobileNumber: 'SignUpWithMobileNumber',
  OTPCode: 'OTPCode',
  CreateNewPassword: 'CreateNewPassword',
  SuccessfulPassword: 'SuccessfulPassword',
  FaceIdScreen: 'FaceIdScreen',
  FingerPrintScreen: 'FingerPrintScreen',
  SelectCountry: 'SelectCountry',
  SelectReason: 'SelectReason',
  CreatePin: 'CreatePin',
  UploadDocument: 'UploadDocument',
  UploadPhotoId: 'UploadPhotoId',
  SelfieWithIdCard: 'SelfieWithIdCard',
  VerifySuccess: 'VerifySuccess',
  FindMyUser: 'FindMyUser',
  RecoveryUserQrpin: 'RecoveryUserQrpin',
  RecoveryUserQrpin2: 'RecoveryUserQrpin2',
  RecoveryQR: 'RecoveryQR',
  RecoveryFinalize: 'RecoveryFinalize',
  RecoveryUser1Pin: 'RecoveryUser1Pin',
  RecoveryUser2Pin: 'RecoveryUser2Pin',
  MyGuardiansStatus: 'MyGuardiansStatus',
};

