export const StackNav = {
  Splash: 'Splash',
  // OnBoarding: 'OnBoarding',
  AuthNavigation: 'AuthNavigation',
  TabNavigation: 'TabNavigation',

  // Nuevas rutas para Mi Voto
  //Subir Acta
  // SubirActa: 'SubirActa',
  BuscarMesa: 'BuscarMesa',
  DetalleMesa: 'DetalleMesa',
  CameraScreen: 'CameraScreen',
  CameraPermissionTest: 'CameraPermissionTest',
  PhotoReviewScreen: 'PhotoReviewScreen',
  PhotoConfirmationScreen: 'PhotoConfirmationScreen',
  // Atestiguar Acta
  AtestiguarActa: 'AtestiguarActa',
  CualEsCorrectaScreen: 'CualEsCorrectaScreen',
  ActaReviewScreen: 'ActaReviewScreen',
  ActaCertificationScreen: 'ActaCertificationScreen',
  // Anunciar Conteo
  AnunciarConteo: 'AnunciarConteo',
  BuscarMesaConteo: 'BuscarMesaConteo',
  DetalleMesaConteo: 'DetalleMesaConteo',
  // Mis Atestiguamientos
  MisAtestiguamientos: 'MisAtestiguamientos',
  MisAtestiguamientosListScreen: 'MisAtestiguamientosListScreen',
  MisAtestiguamientosDetailScreen: 'MisAtestiguamientosDetailScreen',

  StockScreen: 'StockScreen',
  CryptoScreen: 'CryptoScreen',
  NFTsScreen: 'NFTsScreen',
  GoldScreen: 'GoldScreen',
  StocksScreen: 'StocksScreen',
  SearchCryptoSort: 'SearchCryptoSort',
  CryptoDetails: 'CryptoDetails',
  PortfolioOfCrypto: 'PortfolioOfCrypto',
  BuyCrypto: 'BuyCrypto',
  ExchangeCrypto: 'ExchangeCrypto',
  CryptoHistory: 'CryptoHistory',
  MarketSectors: 'MarketSectors',
  SearchStocks: 'SearchStocks',
  DetailsStock: 'DetailsStock',
  StockPortfolio: 'StockPortfolio',
  BuyStock: 'BuyStock',
  ExchangeStock: 'ExchangeStock',
  StockHistory: 'StockHistory',
  PlaceBid: 'PlaceBid',
  CollectionItem: 'CollectionItem',
  ActivityNFts: 'ActivityNFts',
  CollectionItemDetails: 'CollectionItemDetails',
  CreatedByCollection: 'CreatedByCollection',

  //Perfil
  PersonalDetails: 'PersonalDetails',
  RecuperationQR: 'RecuperationQR',
  Reward: 'Reward',
  RewardHistory: 'RewardHistory',
  RewardCode: 'RewardCode',
  Guardians: 'Guardians',
  GuardiansAdmin: 'GuardiansAdmin',
  TransactionHistory: 'TransactionHistory',
  TransactionItem: 'TransactionItem',

  //add guardian
  AddGuardians: 'AddGuardians',

  //Token purchase
  PurchaseTokens: 'PurchaseTokens',
  PurchaseDetails: 'PurchaseDetails',

  //Send/receive tokens
  ReceiveWithQR: 'ReceiveWithQR',
  ReceiveDetails: 'ReceiveDetails',
  ReceiveTokenDetails: 'ReceiveTokenDetails',
  SendDetails: 'SendDetails',
  SendValidation: 'SendValidation',
  SendSuccess: 'SendSuccess',
  SendWithQR: 'SendWithQR',
  SendWithID: 'SendWithID',
  SendWithWallet: 'SendWithWallet',
  SendWalletHelp: 'SendWalletHelp',

  BankAccount: 'BankAccount',
  BankAccountDetails: 'BankAccountDetails',
  AddBankAccount: 'AddBankAccount',
  SelectLanguage: 'SelectLanguage',
  PushNotification: 'PushNotification',
  HelpCenter: 'HelpCenter',
  FAQScreen: 'FAQScreen',
  PrivacyPolicies: 'PrivacyPolicies',
  ChangePinVerify: 'ChangePinVerify',
  ChangePinNew: 'ChangePinNew',
  ChangePinNewConfirm: 'ChangePinNewConfirm',
  TermsAndCondition: 'TermsAndCondition',
  ReferralCode: 'ReferralCode',
  Notification: 'Notification',
  NotificationDetails: 'NotificationDetails',
  GoldDetails: 'GoldDetails',
  AutoInvestGold: 'AutoInvestGold',
  GoldLoan: 'GoldLoan',
  RedeemGold: 'RedeemGold',
  BuyGold: 'BuyGold',
  GoldHistory: 'GoldHistory',
  MyWalletDeposit: 'MyWalletDeposit',
  SelectBankAccountDeposit: 'SelectBankAccountDeposit',
  DepositPreview: 'DepositPreview',
  DepositSuccessful: 'DepositSuccessful',
  MyWalletWithdraw: 'MyWalletWithdraw',
  SelectBankAccountWithdraw: 'SelectBankAccountWithdraw',
  WithdrawSuccessful: 'WithdrawSuccessful',
  SendWallet: 'SendWallet',
  TransferBalance: 'TransferBalance',
  TransferPreview: 'TransferPreview',
  PortfolioHistory: 'PortfolioHistory',
  AboutApp: 'AboutApp',
  HistoryTransactionDetails: ' HistoryTransactionDetails',
  HistoryReport: 'HistoryReport',
  SellStock: 'SellStock',
  SellCrypto: 'SellCrypto',
  WatchListHomeCard: 'WatchListHomeCard',
  StockFutures: 'StockFutures',
  TopGrainers: 'TopGrainers',
  SuccessfulInvest: 'SuccessfulInvest',
  ConditionConfig: 'ConditionConfig',
  Limit: 'Limit',
  Privacy: 'Privacy',
  Security: 'Security',
  Suport: 'Suport',
  Policy: 'Policy',
  //Item secury

  //More
};

export const AuthNav = {
  Connect: 'Connect',
  // Onboarding: 'Onboarding',
  Login: 'Login',
  SignUp: 'SignUp',
  SignUpWithMobileNumber: 'SignUpWithMobileNumber',
  OTPCode: 'OTPCode',
  CreateNewPassword: 'CreateNewPassword',
  SuccessfulPassword: 'SuccessfulPassword',
  FaceIdScreen: 'FaceIdScreen',
  FingerPrintScreen: 'FingerPrintScreen',
  SelectCountry: 'SelectCountry',
  SelectReason: 'SelectReason',
  CreatePin: 'CreatePin',
  UploadDocument: 'UploadDocument',
  UploadPhotoId: 'UploadPhotoId',
  SelfieWithIdCard: 'SelfieWithIdCard',
  VerifySuccess: 'VerifySuccess',
  RegisterUser1: 'RegisterUser1',
  RegisterUser2: 'RegisterUser2',
  RegisterUser3: 'RegisterUser3',
  RegisterUser4: 'RegisterUser4',
  RegisterUser5: 'RegisterUser5',
  RegisterUser6: 'RegisterUser6',
  RegisterUser7: 'RegisterUser7',
  RegisterUser8: 'RegisterUser8',
  RegisterUser9: 'RegisterUser9',
  RegisterUser10: 'RegisterUser10',
  RegisterUser11: 'RegisterUser11',
  LoginUser: 'LoginUser',
  AccountLock: 'AccountLock',
  SelectRecuperation: 'SelectRecuperation',
  ConditionsRegister: 'ConditionsRegister',
};

export const TabNav = {
  HomeScreen: 'HomeScreen',
  MarketScreen: 'MarketScreen',
  WalletScreen: 'WalletScreen',
  PortfolioScreen: 'PortfolioScreen',
  Profile: 'Profile',
  More: 'More',
};
